---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn/longhorn
    repoURL: "https://charts.longhorn.io"
    targetRevision: 1.6.2
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: traefik
          host: longhorn.multipass.local
          tls: true
        preUpgradeChecker:
          jobEnabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
