---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  project: default
  source:
    repoURL: "https://github.com/longhorn/charts.git"
    targetRevision: longhorn-1.6.2
    path: charts/longhorn
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: traefik
          host: longhorn.multipass.local
          tls: true
        preUpgradeChecker:
          jobEnabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  


Unable to load data: error acquiring repo lock: failed to initialize repository resources: rpc error: code = Internal desc = Failed to checkout revision 5001777a2ca01c0fd65cb6292385c75c9e2e9a4e: `git fetch origin 5001777a2ca01c0fd65cb6292385c75c9e2e9a4e --tags --force --prune` failed exit status 128: fatal: remote error: upload-pack: not our ref 5001777a2ca01c0fd65cb6292385c75c9e2e9a4e
