---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: nextcloud
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argo-helm'
    path: charts/argo-cd
    targetRevision: argo-cd-7.3.4
    helm:
      # TODO: Use variables
      values: |
        global:
          domain: argocd.multipass.local
        certificate:
          enabled: false
        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            tls: false
        repoServer:
          extraContainers:
            - name: argocd-repo-server
              image: alpine:3.8
              volumeMounts:
                - name: custom-tools
                  mountPath: /usr/local/bin/argocd-vault-plugin
                  subPath: argocd-vault-plugin
              envFrom:
                - secretRef:
                    name: argocd-vault-plugin-credentials
          volumes:
            - name: custom-tools
              emptyDir: {}
          initContainers:
            - name: download-tools
              image: alpine:3.8
              command: [sh, -c]
              env:
                - name: AVP_VERSION
                  value: "1.16.1"
              args:
                - >-
                  wget -O argocd-vault-plugin
                  https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
                  chmod +x argocd-vault-plugin &&
                  mv argocd-vault-plugin /custom-tools/
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools
        dex:
          enabled: false
        notifications:
          enabled: false
        applicationSet:
          enabled: false
        configs:
          params:
            server.insecure: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
