---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hashicorp/vault-helm'
    path: .
    targetRevision: v0.28.1
    helm:
      # TODO: Use variables
      values: |
        server:
          dataStorage:
            storageClass: longhorn
            size: 1Gi
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - host: vault.multipass.local
          host_aliases:
            - ip: 127.0.0.1
              hostnames:
                - vault.multipass.local

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
