---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-helm
    path: charts/argo-cd
    targetRevision: argo-cd-7.3.4
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # syncPolicy:
  #   automated:
  #     selfHeal: true
